In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.size

3

In [11]:
b.size

6

In [12]:
a.nbytes

12

In [13]:
b.itemsize

4

In [14]:
a = np.array([[1,2,3,7,8,9,0],[4,5,6,11,22,33,44]])
print(a)

[[ 1  2  3  7  8  9  0]
 [ 4  5  6 11 22 33 44]]


In [15]:
a.ndim

2

In [16]:
a[1,5]

33

In [17]:
a[0,6]

0

In [18]:
a[1,-1]

44

In [19]:
a[-1,-1]

44

In [20]:
a[0,:]

array([1, 2, 3, 7, 8, 9, 0])

In [21]:
a[:2]

array([[ 1,  2,  3,  7,  8,  9,  0],
       [ 4,  5,  6, 11, 22, 33, 44]])

In [22]:
a[:1]

array([[1, 2, 3, 7, 8, 9, 0]])

In [23]:
a[:,1]

array([2, 5])

In [24]:
a[0,1:6:2]

array([2, 7, 9])

In [27]:
a[1,3] = 25
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  5  7  8  9  0]
 [ 4  5  5 25 22 33 44]]
[[ 1  2  1  7  8  9  0]
 [ 4  5  2 25 22 33 44]]


In [32]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
c[0,1,0]

3

In [34]:
c[1,1,1]

8

In [35]:
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [37]:
c[:,1,1]

array([4, 8])

In [38]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [42]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [45]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [47]:
np.random.random_sample(a.shape)

array([[0.09317637, 0.37178129, 0.99641884, 0.18916101, 0.45042165,
        0.43434759, 0.87437661],
       [0.75391565, 0.07714844, 0.35673999, 0.55332363, 0.76293598,
        0.53800422, 0.34165971]])

In [52]:
np.random.randint(3,8,size=(3,3))

array([[4, 3, 3],
       [3, 7, 3],
       [3, 7, 7]])

In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [60]:
o = np.ones((5,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [63]:
z[1,1]=9
z


array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [65]:
o[1:4,1:4] = z
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
a = np.array([1,2,3])
b =a.copy
print(b)
a

<built-in method copy of numpy.ndarray object at 0x00000243A8FB8260>


array([1, 2, 3])

In [72]:
a+2

array([3, 4, 5])

In [73]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])